"use client"

import React, { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  X,
  Users,
  Calendar,
  Hash,
  FileText,
  CheckCircle,
  AlertCircle,
  Sparkles,
  Info,
} from "lucide-react";

interface PreYouthBatch {
  id?: string;
  year: number;
  setIdentifier: string;
  description: string;
  status: "Active" | "Completed" | "Archived";
  batchName?: string;
}

interface PreYouthBatchModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (batch: PreYouthBatch) => void;
  batch?: PreYouthBatch | null;
  mode: "create" | "edit";
}

export function PreYouthBatchModal({
  isOpen,
  onClose,
  onSave,
  batch,
  mode,
}: PreYouthBatchModalProps) {
  const currentYear = new Date().getFullYear();

  const [formData, setFormData] = useState<PreYouthBatch>({
    year: currentYear,
    setIdentifier: "",
    description: "",
    status: "Active",
  });

  const [errors, setErrors] = useState<Record<string, string>>({});

  // Initialize form data when batch prop changes or modal opens
  useEffect(() => {
    if (batch && mode === "edit") {
      setFormData({
        id: batch.id,
        year: batch.year,
        setIdentifier: batch.setIdentifier,
        description: batch.description,
        status: batch.status,
      });
    } else if (mode === "create") {
      setFormData({
        year: currentYear,
        setIdentifier: "",
        description: "",
        status: "Active",
      });
    }
    setErrors({});
  }, [batch, mode, isOpen, currentYear]);

  // Auto-generate batch name based on format: PY + Year + SET + Number
  const generateBatchName = (year: number, setId: string): string => {
    if (!year || !setId) return "PY____SET__";
    return `PY${year}SET${setId}`;
  };

  const autoGeneratedName = generateBatchName(
    formData.year,
    formData.setIdentifier,
  );

  const validateForm = (): boolean => {
    const newErrors: Record<string, string> = {};

    if (!formData.year) {
      newErrors.year = "Batch year is required";
    } else if (formData.year < 2000 || formData.year > 2100) {
      newErrors.year = "Year must be between 2000 and 2100";
    }

    if (!formData.setIdentifier) {
      newErrors.setIdentifier = "Set identifier is required";
    } else if (!/^\d+$/.test(formData.setIdentifier)) {
      newErrors.setIdentifier = "Set identifier must be a number";
    }

    if (!formData.description.trim()) {
      newErrors.description = "Description is required";
    } else if (formData.description.trim().length < 10) {
      newErrors.description = "Description must be at least 10 characters";
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!validateForm()) {
      return;
    }

    const batchData: PreYouthBatch = {
      ...formData,
      batchName: autoGeneratedName,
    };

    onSave(batchData);
    handleClose();
  };

  const handleClose = () => {
    setFormData({
      year: currentYear,
      setIdentifier: "",
      description: "",
      status: "Active",
    });
    setErrors({});
    onClose();
  };

  const handleInputChange = (field: keyof PreYouthBatch, value: any) => {
    setFormData((prev) => ({
      ...prev,
      [field]: value,
    }));

    // Clear error for this field when user starts typing
    if (errors[field]) {
      setErrors((prev) => {
        const newErrors = { ...prev };
        delete newErrors[field];
        return newErrors;
      });
    }
  };

  if (!isOpen) return null;

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/50 z-40 backdrop-blur-sm"
        onClick={handleClose}
      />

      {/* Modal */}
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
        <Card className="w-full max-w-2xl bg-white shadow-xl max-h-[90vh] overflow-y-auto">
          <CardHeader className="border-b border-[#EDF1F7] sticky top-0 bg-white z-10">
            <div className="flex items-start justify-between">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-lg bg-purple-50 flex items-center justify-center">
                  <Users className="w-6 h-6 text-purple-600" />
                </div>
                <div>
                  <CardTitle className="text-xl text-[#222B45]">
                    {mode === "create"
                      ? "Create Pre-Youth Batch"
                      : "Edit Pre-Youth Batch"}
                  </CardTitle>
                  <p className="text-sm text-[#8F9BB3] mt-1">
                    {mode === "create"
                      ? "Set up a new Pre-Youth Class batch for the year"
                      : "Update batch information and settings"}
                  </p>
                </div>
              </div>
              <button
                onClick={handleClose}
                className="text-[#8F9BB3] hover:text-[#222B45] transition-colors p-1"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
          </CardHeader>

          <form onSubmit={handleSubmit}>
            <CardContent className="p-6 space-y-6">
              {/* Auto-Generated Batch Name Display */}
              <div className="p-4 bg-linear-to-r from-purple-50 to-blue-50 border-2 border-dashed border-purple-200 rounded-lg">
                <div className="flex items-start gap-3">
                  <div className="w-10 h-10 rounded-lg bg-purple-100 flex items-center justify-center shrink-0">
                    <Sparkles className="w-5 h-5 text-purple-600" />
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-2">
                      <h4 className="text-sm font-semibold text-purple-900">
                        Auto-Generated Batch Name
                      </h4>
                      <Badge
                        variant="outline"
                        className="bg-purple-100 text-purple-700 border-purple-300 text-xs"
                      >
                        System Generated
                      </Badge>
                    </div>
                    <div className="flex items-center gap-3 mb-2">
                      <code className="text-lg font-mono font-semibold text-purple-900 bg-white px-3 py-2 rounded border border-purple-200">
                        {autoGeneratedName}
                      </code>
                      {formData.year && formData.setIdentifier && (
                        <CheckCircle className="w-5 h-5 text-green-600" />
                      )}
                    </div>
                    <p className="text-xs text-purple-700">
                      <span className="font-medium">Format:</span> PY (Prefix) +{" "}
                      {formData.year || "YYYY"} (Year) + SET +{" "}
                      {formData.setIdentifier || "XX"} (Number)
                    </p>
                  </div>
                </div>
              </div>

              {/* Information Banner */}
              <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg">
                <div className="flex items-start gap-2">
                  <Info className="w-4 h-4 text-blue-600 shrink-0 mt-0.5" />
                  <p className="text-xs text-blue-700">
                    The batch name is automatically generated based on the year
                    and set identifier. Manual naming is not available to ensure
                    consistency across the system.
                  </p>
                </div>
              </div>

              {/* Batch Year */}
              <div>
                <label className="block text-sm font-medium text-[#222B45] mb-2">
                  <div className="flex items-center gap-2">
                    <Calendar className="w-4 h-4 text-[#009AF4]" />
                    Batch Year
                    <span className="text-red-500">*</span>
                  </div>
                </label>
                <input
                  type="number"
                  value={formData.year}
                  onChange={(e) =>
                    handleInputChange("year", parseInt(e.target.value))
                  }
                  min="2000"
                  max="2100"
                  className={`w-full px-4 py-2.5 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[#009AF4] transition-all ${
                    errors.year
                      ? "border-red-300 bg-red-50"
                      : "border-[#EDF1F7] bg-white"
                  }`}
                  placeholder="e.g., 2025"
                />
                {errors.year && (
                  <div className="flex items-center gap-1 mt-1.5 text-red-600">
                    <AlertCircle className="w-3.5 h-3.5" />
                    <p className="text-xs">{errors.year}</p>
                  </div>
                )}
                <p className="text-xs text-[#8F9BB3] mt-1.5">
                  The year this Pre-Youth batch will run (e.g., 2025 for the
                  2025 batch)
                </p>
              </div>

              {/* Set Identifier */}
              <div>
                <label className="block text-sm font-medium text-[#222B45] mb-2">
                  <div className="flex items-center gap-2">
                    <Hash className="w-4 h-4 text-[#009AF4]" />
                    Set Identifier
                    <span className="text-red-500">*</span>
                  </div>
                </label>
                <input
                  type="text"
                  value={formData.setIdentifier}
                  onChange={(e) =>
                    handleInputChange("setIdentifier", e.target.value)
                  }
                  className={`w-full px-4 py-2.5 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[#009AF4] transition-all ${
                    errors.setIdentifier
                      ? "border-red-300 bg-red-50"
                      : "border-[#EDF1F7] bg-white"
                  }`}
                  placeholder="e.g., 34"
                  maxLength={4}
                />
                {errors.setIdentifier && (
                  <div className="flex items-center gap-1 mt-1.5 text-red-600">
                    <AlertCircle className="w-3.5 h-3.5" />
                    <p className="text-xs">{errors.setIdentifier}</p>
                  </div>
                )}
                <p className="text-xs text-[#8F9BB3] mt-1.5">
                  A unique numeric identifier for this set (e.g., 34 for the
                  34th set)
                </p>
              </div>

              {/* Description */}
              <div>
                <label className="block text-sm font-medium text-[#222B45] mb-2">
                  <div className="flex items-center gap-2">
                    <FileText className="w-4 h-4 text-[#009AF4]" />
                    Description
                    <span className="text-red-500">*</span>
                  </div>
                </label>
                <textarea
                  value={formData.description}
                  onChange={(e) =>
                    handleInputChange("description", e.target.value)
                  }
                  rows={4}
                  className={`w-full px-4 py-2.5 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[#009AF4] transition-all resize-none ${
                    errors.description
                      ? "border-red-300 bg-red-50"
                      : "border-[#EDF1F7] bg-white"
                  }`}
                  placeholder="Provide a brief description of this batch, including key objectives, target age group, or any special notes..."
                />
                {errors.description && (
                  <div className="flex items-center gap-1 mt-1.5 text-red-600">
                    <AlertCircle className="w-3.5 h-3.5" />
                    <p className="text-xs">{errors.description}</p>
                  </div>
                )}
                <div className="flex items-center justify-between mt-1.5">
                  <p className="text-xs text-[#8F9BB3]">
                    Provide details about this batch and its objectives
                  </p>
                  <p className="text-xs text-[#8F9BB3]">
                    {formData.description.length} characters
                  </p>
                </div>
              </div>

              {/* Status */}
              <div>
                <label className="block text-sm font-medium text-[#222B45] mb-2">
                  <div className="flex items-center gap-2">
                    <CheckCircle className="w-4 h-4 text-[#009AF4]" />
                    Status
                    <span className="text-red-500">*</span>
                  </div>
                </label>
                <div className="grid grid-cols-3 gap-3">
                  <button
                    type="button"
                    onClick={() => handleInputChange("status", "Active")}
                    className={`p-4 border-2 rounded-lg transition-all ${
                      formData.status === "Active"
                        ? "border-green-500 bg-green-50"
                        : "border-[#EDF1F7] bg-white hover:border-green-200"
                    }`}
                  >
                    <div className="flex flex-col items-center gap-2">
                      <div
                        className={`w-10 h-10 rounded-full flex items-center justify-center ${
                          formData.status === "Active"
                            ? "bg-green-100"
                            : "bg-gray-100"
                        }`}
                      >
                        <CheckCircle
                          className={`w-5 h-5 ${formData.status === "Active" ? "text-green-600" : "text-gray-400"}`}
                        />
                      </div>
                      <span
                        className={`text-sm font-medium ${
                          formData.status === "Active"
                            ? "text-green-700"
                            : "text-[#8F9BB3]"
                        }`}
                      >
                        Active
                      </span>
                    </div>
                  </button>

                  <button
                    type="button"
                    onClick={() => handleInputChange("status", "Completed")}
                    className={`p-4 border-2 rounded-lg transition-all ${
                      formData.status === "Completed"
                        ? "border-blue-500 bg-blue-50"
                        : "border-[#EDF1F7] bg-white hover:border-blue-200"
                    }`}
                  >
                    <div className="flex flex-col items-center gap-2">
                      <div
                        className={`w-10 h-10 rounded-full flex items-center justify-center ${
                          formData.status === "Completed"
                            ? "bg-blue-100"
                            : "bg-gray-100"
                        }`}
                      >
                        <CheckCircle
                          className={`w-5 h-5 ${formData.status === "Completed" ? "text-blue-600" : "text-gray-400"}`}
                        />
                      </div>
                      <span
                        className={`text-sm font-medium ${
                          formData.status === "Completed"
                            ? "text-blue-700"
                            : "text-[#8F9BB3]"
                        }`}
                      >
                        Completed
                      </span>
                    </div>
                  </button>

                  <button
                    type="button"
                    onClick={() => handleInputChange("status", "Archived")}
                    className={`p-4 border-2 rounded-lg transition-all ${
                      formData.status === "Archived"
                        ? "border-gray-500 bg-gray-50"
                        : "border-[#EDF1F7] bg-white hover:border-gray-200"
                    }`}
                  >
                    <div className="flex flex-col items-center gap-2">
                      <div
                        className={`w-10 h-10 rounded-full flex items-center justify-center ${
                          formData.status === "Archived"
                            ? "bg-gray-200"
                            : "bg-gray-100"
                        }`}
                      >
                        <CheckCircle
                          className={`w-5 h-5 ${formData.status === "Archived" ? "text-gray-600" : "text-gray-400"}`}
                        />
                      </div>
                      <span
                        className={`text-sm font-medium ${
                          formData.status === "Archived"
                            ? "text-gray-700"
                            : "text-[#8F9BB3]"
                        }`}
                      >
                        Archived
                      </span>
                    </div>
                  </button>
                </div>
                <p className="text-xs text-[#8F9BB3] mt-2">
                  Select the current status of this batch
                </p>
              </div>

              {/* Form Summary */}
              <div className="p-4 bg-[#F7F9FC] border border-[#EDF1F7] rounded-lg">
                <h4 className="text-sm font-semibold text-[#222B45] mb-3">
                  Batch Summary
                </h4>
                <div className="space-y-2 text-sm">
                  <div className="flex items-center justify-between">
                    <span className="text-[#8F9BB3]">Generated Name:</span>
                    <code className="font-mono font-medium text-[#222B45]">
                      {autoGeneratedName}
                    </code>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-[#8F9BB3]">Year:</span>
                    <span className="font-medium text-[#222B45]">
                      {formData.year}
                    </span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-[#8F9BB3]">Set ID:</span>
                    <span className="font-medium text-[#222B45]">
                      {formData.setIdentifier || "—"}
                    </span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-[#8F9BB3]">Status:</span>
                    <Badge
                      variant="outline"
                      className={
                        formData.status === "Active"
                          ? "bg-green-50 text-green-700 border-green-200"
                          : formData.status === "Completed"
                            ? "bg-blue-50 text-blue-700 border-blue-200"
                            : "bg-gray-50 text-gray-700 border-gray-200"
                      }
                    >
                      {formData.status}
                    </Badge>
                  </div>
                </div>
              </div>
            </CardContent>

            {/* Footer Actions */}
            <div className="border-t border-[#EDF1F7] p-6 bg-[#F7F9FC] flex items-center justify-end gap-3 sticky bottom-0">
              <Button
                type="button"
                onClick={handleClose}
                variant="outline"
                className="min-w-25"
              >
                Cancel
              </Button>
              <Button
                type="submit"
                className="bg-[#009AF4] hover:bg-[#0086D6] text-white min-w-25"
              >
                <CheckCircle className="w-4 h-4 mr-2" />
                {mode === "create" ? "Create Batch" : "Save Changes"}
              </Button>
            </div>
          </form>
        </Card>
      </div>
    </>
  );
}
